### ISSUE TITLE
Please support feature retina for Mac

### ISSUE THREAD

**Issue by solokop** [UnderwaterApps/overlap2d-runtime-libgdx#18]
It's better to look at the screen with true resolution of arts.

**Comment by azakhary** [comment]
We are going to open source the editor soon here on github, when done, I will move this issue there. 
Thanks for bringing this up!

**Comment by azakhary** [comment]
Closing this one, issue was duplicated in 
https://github.com/UnderwaterApps/overlap2d/issues/51
