### ISSUE TITLE
Sprite frame named *000.png 

### ISSUE THREAD

**Issue by Hohenheimsenberg** [UnderwaterApps/overlap2d-runtime-libgdx#20]
As I explained [here](https://github.com/UnderwaterApps/overlap2d/issues/49), I have a sprite animation with names starting from 0: image000, image001, image00n.

[SpriteAnimation.java](https://github.com/UnderwaterApps/overlap2d-runtime-libgdx/blob/master/src/com/uwsoft/editor/renderer/actor/SpriteAnimation.java#L105) throws an error because of the "000" frame.

**Comment by azakhary** [comment]
merged in #22
