### ISSUE TITLE
R.U.B.E

### ISSUE THREAD

**Issue by andrewtheone** [UnderwaterApps/overlap2d-runtime-libgdx#32]
You should add RUBE into overlap2d, it'll be fun to be able to create physics scenes in RUBE then import it into overlap2d and add scripts to different objects.

https://www.iforce2d.net/rube/

**Comment by azakhary** [comment]
I totally want to, it's just the amount of things we should add is huge :D

**Comment by andrewtheone** [comment]
actually, the main point is all set up, its not have to be rube.. but an extended physics editor.

Look at BuildBox, you could copy a few things, for example the drag and drop wheel, and physics editor, those would be cool.

btw: when will be have the newest version of the editor? and runtime?

**Comment by azakhary** [comment]
True.

I am bad at keeping promises for release dates. At this moment it is looking like several weeks. like 3 weeks maybe :) This though will be a very big update, maybe one of the biggest ones. in terms of entire code overhaul, ui changes, and most importantly the strong foundation, to build up new features with easy. You will not recognize it. :)
