### ISSUE TITLE
Several Issues regarding VO's and Actors

### ISSUE THREAD

**Issue by azakhary** [UnderwaterApps/overlap2d-runtime-libgdx#46]
I am just copy pasting bugs reported by Krismu in the forums.
------------------------------------------------------------------------------

Bug in the MainItemVo constructor:

if(tags != null) tags = Arrays.copyOf(vo.tags, vo.tags.length);

should be replaced with:
if(vo.tags != null) tags = Arrays.copyOf(vo.tags, vo.tags.length);

And initialization of CompositeActor in processMain() should copy the item identifier to the Actor’s name, it would make multiple levels children search a lot easier. It should not have any side effect because the name is not set or used anywhere else, as far as I know.

Thanks

**Comment by KrissMu** [comment]
Hi,
Long time since I've reported these issues. I've updated to 0.1.2 and I expected this to be solved, but it isn't yet.
Any chance to see this simple thing corrected any time soon ?
Is the project still in development ?

**Comment by azakhary** [comment]
Merged in #90
