### ISSUE TITLE
cant see overlap2d-runtime lib in libgdx project folder

### ISSUE THREAD

**Issue by bangive** [UnderwaterApps/overlap2d-runtime-libgdx#60]
I use gradle to install runtime 0.1.2-snapshot but cant see it in libgdx project folder

**Comment by azakhary** [comment]
it should not appear in any folder.

**Comment by bangive** [comment]
So where it is installed, how to check if it is installed.

**Comment by azakhary** [comment]
Gradle downloads libraries from maven central to your user folder .gradle/cache somewhere here it resides. What IDE are you using? when you import a gradle project things should work all by themselves. Here, check out the video of me doing the process, to see if you did all correct: https://www.youtube.com/watch?v=bhvHm2sM0qo (note that 0.1.2-SNAPSHOT is the correct version, but it was released after this video was made) Let me know if this helps.

**Comment by bangive** [comment]
Thank you so much, i already use 0.1.2-SNAPSHOT in gradle. Why you don't update this version in readme, the current version in readme is 0.1.1-SNAPSHOT and gradle can not find it. I will check your video.

**Comment by azakhary** [comment]
oh, oups, the readme has to be updated, did not remember that one, thanks a lot for bringing this up!

**Comment by bangive** [comment]
Have you updated it yet. It still show compile "com.underwaterapps.overlap2druntime:overlap2d-runtime-libgdx:0.1.1-SNAPSHOT

**Comment by azakhary** [comment]
just 10 seconds ago :)

**Comment by bangive** [comment]
The problem is solved. Thank you again.
