### ISSUE TITLE
overlap2d-runtime-libgdx doesn't work without freetype and box2D?

### ISSUE THREAD

**Issue by ihitang** [UnderwaterApps/overlap2d-runtime-libgdx#65]
I'm trying to reduce apk size. I don't use box2D in my game. 
Is there any possibility to exclude box2D from overlap2d-runtime-libgdx?

> java.lang.ExceptionInInitializerError at com.uwsoft.editor.renderer.SceneLoader.initSceneLoader(SceneLoader.java:83)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'gdx-box2d' for target: Linux, 32-bit

**Comment by azakhary** [comment]
You can make your own scene loader (by copying the original one, and remove all physics references from there, including Physics System and lights stuff)

**Comment by ihitang** [comment]
Ok, I'll try it, thanks

**Comment by zssMostE** [comment]
> Ok, I'll try it, thanks

Did you make you own scene?Could you give me your code?

**Comment by zssMostE** [comment]
@ihitang Did you make you own scene?Could you give me your code?
