### ISSUE TITLE
Double creating of spriterAnimations

### ISSUE THREAD

**Issue by Pretzel777** [UnderwaterApps/overlap2d-runtime-libgdx#66]
EntityFactory line 299.
for (int i = 0; i < vo.sSpriterAnimations.size(); i++) { 
Entity child = createEntity(entity, vo.sSpriterAnimations.get(i)); engine.addEntity(child); 
}
is duplicated.

**Comment by azakhary** [comment]
Hi, could you do a pull request so I can merge your changes right away?

**Comment by Pretzel777** [comment]
Hi, yes sure. Maked pull request right now. Is it all ok?

**Comment by azakhary** [comment]
hmm. no no marking, 
Pull Requests are suggestions of code change, made from your Fork to main repo here, https://github.com/UnderwaterApps/overlap2d-runtime-libgdx/pulls

Usually when someone notices a necessary code change, they can change that on their fork of this repo, and then use create pull request button to propose the change, I (and/or others) then can review the proposed change, and merge is it makes sense.

**Comment by azakhary** [comment]
There is an easier way to do it by guithub, you can click "edit" the file here on github, and then it will create the pull request for you.

**Comment by azakhary** [comment]
Here, read this: https://help.github.com/articles/editing-files-in-another-user-s-repository/

**Comment by Pretzel777** [comment]
Ok, thanks for information. Maked it by edit on github.

**Comment by j3zequiel** [comment]
Is this already fixed? because i refresh dependencies and still is duplicated. Thanks

**Comment by azakhary** [comment]
Just baked the latest build to maven central, will take 5 minutes or so (make sure to clear caches) marking it as resolved.
