### ISSUE TITLE
[REQUEST] Maven repo

### ISSUE THREAD

**Issue by FranciscoEstevez** [UnderwaterApps/overlap2d-runtime-libgdx#7]
Could you please put the project in Sonatype?

**Comment by azakhary** [comment]
am I too late? I guess I am to late. but, here - com.underwaterapps.overlap2druntime

**Comment by FranciscoEstevez** [comment]
It's never too late for this things, thank you and congrats on the 0.0.7 release!

**Comment by azakhary** [comment]
Thank you!
