### ISSUE TITLE
Add a proper License

### ISSUE THREAD

**Issue by Sleaker** [UnderwaterApps/overlap2d-runtime-libgdx#8]
The code repository & website lack what license the software & source are released under.  While it's available freely and forkable on github this does not necessarily mean I can do anything with it.  It would be helpful to indicate what the license is to let us know what we can and can't do with the source here. 

Thanks

**Comment by azakhary** [comment]
Totally agree (and sorry for the late reply) 
I need to dig in to figure out which license to use. But as for now there is no limitations on what you can do with runtime code.

**Comment by azakhary** [comment]
It is done. The mighty license has been set.

**Comment by Sleaker** [comment]
Thanks much!
