### ISSUE TITLE
Crash when pressing root element in elements tree

### ISSUE THREAD

**Issue by vlebedynskyi** [UnderwaterApps/overlap2d-runtime-libgdx#9]
When I am trying to select root element(actually i am trying to set background for it, if it is possible) Overlap2D says: "We are so embarrassed.... run this app again".

Here is screenshot http://screencloud.net/v/uqZg

OS - Ubutu 14.04
Java: java version "1.7.0_72"
Java(TM) SE Runtime Environment (build 1.7.0_72-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.72-b04, mixed mode)

**Comment by azakhary** [comment]
Fixed in 0.0.7 :) Thanks for reporting
